### ISSUE TITLE
How to disable or do not display the little middle marker of polyline? 

### ISSUE THREAD

**Issue by davidbrave** [codeofsumit/leaflet.pm#411]

**Comment by codeofsumit** [comment]
can you please provide a screenshot of what exactly you want to hide?

**Comment by davidbrave** [comment]
![image](https://user-images.githubusercontent.com/18387424/56077977-0c961f80-5e15-11e9-8407-b49fbd9c2062.png)

**Comment by codeofsumit** [comment]
You can hide them via CSS

```css
.marker-icon-middle {
    display: none;
}
```
